# Generated by Django 2.2.6 on 2022-09-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220927_0540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписки'},
        ),
    ]
